package me.duncte123.io.hirobs

fun randomDeadChat(): String =  listOf(
    "If two witches were to watch two watches, then which witch would watch which watch?",
    "Have you guys played any visual novels other than Camp Buddy? I've heard Bacchikoi is a good one.",
    "Would you rather fight one bear sized frog, or 100 frog sized bears?",
    "I'm hungry. What's your favourite food?",
    "How's the weather? ( ͡° ͜ʖ ͡°)",
    "Thoughts on the most recent reward __preview__?",
    "I wonder what Mikko is doing...",
    "Would definitely be livelier with Jey around~",
    "Tch, blame wolfboy.",
    "It's because of Natsumi, he had everybody clean Mess Hall.",
    "What are some recipes you can easily make while on a camping trip?",
    // YIAY questions :)
    "What would you do if you won the Super Bowl?",
    "What book deserves a sequel, and what's its title?",
    "What is the best way to dump someone?",
    "What flavor of Oreo cookie do **you** want to see?",
    "If you could change any movie ending, what would you change?",
    "What song do you party to?",
    "What's your weapon of choice in the zombie apocalypse?",
    "What's the best way to tell your crush that you like them?",
    "Write the loveliest \"roses are red\" poem.",
    "What's a good acronym for LOVE?",
    "Can you describe YouTube in 4 words?",
    "What is the meanest insult without curse words?",
    "Who would you thank in your acceptance speech?",
    "What is your biggest fear?",
    "What turns you on?",
    "What would your last words be?",
    "In 4 words, what is the meaning of life?",
    "If you could time travel, where would you go and what would you do?",
    "What's your best \"yo momma\" joke?",
    "What song do you want played at your funeral?",
    "What are some \"Top 10\" lists you would like to see?",
    "If you had 100 million Twitter followers, what would you tweet?",
    "What movie deserves a sequel? What's its title?",
    "What's the first thing you do when you wake up?",
    "Fil in the blank: I love you more than _____.",
    "What would your wrestler name be, and what's your finishing move?",
    "What's a great April Fool' Day prank?",
    "Write a sad story in 4 words",
    "Write a haiku about your favorite video game",
    "Why do we love taking selfies so much?",
    "What feature would you like to see in your next smartphone?",
    "What video game should be made into a movie?",
    "If your pet could talk, what would it say?",
    "Describe the internet in 4 words",
    "What's your yearbook quote?",
    "What turns you off?",
    "What are some great workout tips?",
    "What are your best life hacks?",
    "What's the best way to wake up Yoichi?",
    "How do you impress a guy?",
    "Fill in the blank: \"We go together like ____ and ____.\"",
    "Ruin a relationship in 4 words",
    "What's the best way to quit your job?",
    "What are some cool new swear words?",
    "What are the rules of the internet?",
    "Worst thing to say on a first date?",
    "What's your best kickstarter idea?",
    "Blow my mind in 6 words or less",
    "What's your dream fight?",
    "What's your best motivational quote?",
    "When did you realize you weren't a kid anymore?",
    "What are your relationship goals?",
    "Describe facebook in 4 words",
    "Last-minute Mother's Day gift ideas?",
    "What word/phrase should officially be retired?",
    "What's your favorite thing to do in bed?",
    "What would you do if you had a cloning machine?",
    "What's the best way to cheer someone up?",
    "If you were a superhero, what would your name and superpower be?",
    "How do you escape the friendzone?",
    "Fill in the blank: A ____ a day keeps the doctor away",
    "What's the worst thing to say at a funeral?",
    "What annoys you the most?",
    "How do you want to die?",
    "How to be a thug in 4 words?",
    "If you were immortal for a day, what would you do?",
    "What's the worst time to faint?",
    "How would you break the internet?",
    "What are you doing this weekend?",
    "What's a new acronym for PETA?",
    "What are some new Starbucks flavors?",
    "What are your best tips for a job interview?",
    "What are your best ice breakers?",
    "If you were a world-class hacker, what would you hack into?",
    "What's on your bucket list?",
    "What are your best dad jokes?",
    "Describe teenagers in 4 words",
    "What are your best parenting tips?",
    "What's an acronym for memes?",
    "Describe Disney in 4 words",
    "What would **you** tell the haters?",
    "When is the worst time to get a call from your grandmother?",
    "How do you sleep at night?",
    "If you could shrink in size, what would you do?",
    "What's the coolest thing to say while walking away from an explosion?",
    "What are your best dieting tips?",
    "Where do babies come from?",
    "What would you say to your 100-year-old self?",
    "Write a moving story in 10 words",
    "What is your nerdiest joke?",
    "What's a new acronym for YOLO?",
    "If you were invisible for a day, what would you do?",
    "Meanest insults without cursing?",
    "Get rick quick tips?",
    "If a genie granted you 1 wish, what would you wish for?",
    "What are some honest product slogans?",
    "What can you say about a car, that you can't say about your boyfriend?",
    "Describe Apple in 4 words?",
    "What's your best hangover cure?",
    "What's your best band name?",
    "The internet's down for a week. What do you do?",
    "Fill in the blank! You know what they say: ____",
    "Describe the 90's in 4 words",
    "What would you do if you had a million dollars?",
    "What are some tips on becoming popular?",
    "What's the worst thing to say at a wedding?",
    "What would you do if you were the last person on Earth?",
    "What are the rules of YouTube?",
    "What's your theme song?",
    "What's one thing he hates to see in the bedroom?",
    "What are some tips on surviving college?",
    "What are your most useful studying tips?",
    "What is happiness in 4 words",
    "Fill in the blank: When life gives you lemons, ____",
    "What's the best way to propose to someone?",
    "How do you take the perfect selfie?",
    "What should a smartwatch do?",
    "What are some new world-changing inventions?",
    "What's the best way to avoid spoilers",
    "Describe fall/autumn in 4 words",
    "Fill in the blank: Keep calm and ____",
    "What are your best shaving tips?",
    "You just got dumped. What do you do?",
    "What's your life motto?",
    "What's a new flavor for a protein bar?",
    "Write a haiku about your favorite movie",
    "Describe reddit in 4 words",
    "What are your best traveling tips?",
    "What is the best day to spend a Friday?",
    "If you could bring 1 item to a deserted island, what would it be?",
    "What's a new award category for the Oscars?",
    "When is the worst time to sneeze?",
    "Fill in the blank: If you can't beat 'em, ____",
    "What are some tips for writing a hit song?",
    "What new filter should they add to smartphones?",
    "What's your Halloween costume?",
    "Describe the '00s in 4 words",
    "What are the best themes for a birthday party?",
    "What are some clichés in anime?",
    "Design a new flag for Antarctica!",
    "What are you thankful for?",
    "What are some Black Friday shopping tips?",
    "Describe Twitter in 4 words",
    "Fill in the blank: Damn girl, are you ____? Because ____!",
    "Describe Christmas in 4 words!",
    "What are some of life's ultimate burning questions that need answering?",
    "What is love in 4 words?",
    "Fill in the blank: All I want fir Christmas is ____",
    "Summarize Star Wars in 1 sentence",
    "What are some new baby names?",
    "What's an acronym for DRUNK?",
    "Describe winter in 4 words",
    "Fill in the blank: If it ain't broke, ___",
    "If you had 100 million subscribers on YouTube, what's your next video?",
    "If you could be anyone else for a day, who would you be?",
    "What are some alternatives to Netflix and chill?",
    "How to be funny in 4 words?",
    "What's an acronym for VOTE?",
    "What's an alternative title for Deadpool?",
    "What's the best way to get over your ex?",
    "Lose your friends in 4 words!",
    "Fill in the blank: Life is like a box of chocolates: ____",
    "Fun things to do with your parents?",
    "What's your worst compliment?",
    "What is your deepest, darkest secret?",
    "What is a good alternative to the phrase \"Grinds My Gears\"?",
    "Describe Hollywood in 4 words",
    "How to be a good mother?",
    "What makes you happy in just 4 words?",
    "Fill in the blanks: I love you like ____ loves ____!",
    "Describe your morning in just 4 words",
    "Where's the worst place to play Pokemon GO?",
    "Describe your ex in 4 words",
    "How do you get ready for a first date?",
    "Disappoint your parents, in just 4 words",
    "When is the worst time to say \"Y-you too\" to someone?",
    "When is something no longer cool?",
    "What will the most poplar trends be in 2020?",
    "How would you break up with your S/O if you found someone else?",
    "What's the sluttiest thing you've done today?",
    "What are the Top 20 achievements of humanity?",
    "Come up with the opposite of \"that really grinds my gears\"",
    "What's another meme-stealing phrase like \"who did this\"?",
    "Fill in the blank: Ok Google: ____",
    "Make up your best \"fake facts\"",
    "What are some mild challenges?",
    "Fill in the blanks: A group of ____ is called a ____.",
    "Write the next line: \"My name is Eminem and I'm here to say ____\"",
    "Fill in the blank: \"____\" lied the YouTuber",
    "Fill in the blank: Wanna feel old? ____",
    "What are some events we can count down to?",
    "What's the plot for Shrek 5?",
    "When is the worst time to say \"I love you\"?",
    "What's something you wish your smartphone could do?",
    "What are some creative poses for group photos/meet'n'greets?",
    "What does E3 stand for?",
    "What's Mario's catchphrase?",
    "Describe Game of Thrones in just 1 sentence!",
    "If you were a candle, what scent would you be?",
    "How do you stay safe from hackers?",
    "Millennials in just 4 words?",
    "What's your billion dollar movie idea?",
    "What if the haters dab back?",
    "What is your biggest regret?",
    "Give me some *totally legit* British slang",
    "What are some fake movie quotes that include the title of the movie?",
    "What's the most basic thing you've ever done?",
    "What word/phrase do you say when you're pissed off?",
    "What do you need to start a YouTube channel?",
    "What are the top Halloween costumes this year?",
    "If you could travel in time, how would you mess with it?",
    "What's the point?",
    "What are some last-minute Halloween costumes?",
    "What's the best way to get a party started?",
    "Describe yourself using emojis",
    "What are you thankful for?",
    "You just got a book deal. What's your book about?",
    "Who should TIME Magazine's \"Person of the Year\" be?",
    "What do you want for Christmas?",
    "What does the FCC stand for?",
    "When did you stop believing in Santa?",
    "What's the worst gift you got for Christmas?",
    "What are your new year's resolutions?",
    "What are some examples of microcheating?",
    "What does BTS stand for?",
    "What should I do if I win YouTuber of the Year?",
    "If you could chat with anyone, who would it be?",
    "What's your underdog story?",
    "Who would win in a fight: Superman, Wonder Woman, or Batman?",
    "What's the worst thing you've ever done?",
    "Title for the next Avengers movie?",
    "Name 3 characters from the film Avatar (2009)",
    "Can you guess the movie in just 4 words?",
    "If you could teleport, what would you do?",
    "Where's the worst place you could teleport?",
    "What does IHOB really stand for?",
    "Who was your first crush?",
    "What's your supervillain name and power?",
    "If you could spy on anyone/anything, how would you use it?",
    "What're you super duper sorry for?",
    "Fill in the blank! I'm a 90s kid, and I love ____.",
    "In just 4 words, describe the perfect viral video!",
    "Describe the new iPhone in just 4 words!",
    "Fill in the blank: I hate it when YouTubers: ____.",
    "Sum up your personality in just 4 words",
    "In just 4 words, what's your Halloween costume?",
    "What are some tips on living a healthier lifestyle?",
    "What are some new categories for a web awards show?",
    "What are your best tips on becoming an influencer?",
    "What's your TED Talk about?",
    "Who is the next fighter in Smash Bros?",
    "You just got $300. What do you do with it?",
    "What will be the the post-credits scene for Avengers: Endgame?",
    "How will Game of Thrones end?",
    "What's the worst possible YouTuber merch?",
    "What would you do if Fortnite took your move?",
    "What's actually in Area 51?",
    "What's the worst thing to hear from your Uber driver?",
    "What's your signature catchphrase?",
    "Describe boomers in just 4 words",
    "Describe the 2010s ...in just 4 words!",
    "Oh no, you just got cancelled. What do you do now?",
    "How should I tell our dogs they're adopted?",
    "Help me write a Christmas song!",
    "What's your billion dollar app idea?",
    "What creeps you out?",
    "What does simp stand for?",
    "What would a figurine of yourself look like?",
    "What wil be the plot of Avatar 2?",
    "How would you explain TikTok to your grandmother?",
    "YouTube 2.0 just came out; what's its big feature?",
    "Describe the PS5 in just 4 words",
    "What exactly is a \"bruh moment\"?",
    "What's a news headline you'd love to see?",
    "Describe The Boys in just 4 words!",
    "What's the worst Christmas gift you got this year?",
    "Fill in the blank: Women be shoppin, men be ____.",
    "What videogame quote brings you to tears?",
    "Fill in the blank: THIS JUST IN: ____",
    "Hooray! You finally got vaccinated! WHat's the first thing you'll do?",
    "What new feature should Twitter 2.0 have?",
    "What's the difference between Millenials and Gen z?",
    "You're now the host of Ellen! What's your show like?",
    "What's a neat life hack you know?",
    "You just opened a new restaurant. What's it called, and what are you serving?",
    "What does Dad want for Father's Day?",
    "What exactly is a girlboss?",
    "If Heaven is real, what's it like?",
    "You're now the host of Jeopardy, what new rule will you add?",
    "If the answer is Jacksfilms, what's the question?",
    "What's the Joker's signature catchphrase?",
    "in just 4 words, describe the Nintendo Switch OLED Model",
    "What does GAMER stand for?",
    "What's a cool thing to say while breaking up with your partner?",
).random()
