name: Compile code

on:
    push:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to Github packages
                uses: docker/login-action@v2
                with:
                    username: duncte123
                    password: ${{ secrets.DOCKER_TOKEN }}

            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: false
                    tags: duncte123/superhiro:beta
                    cache-from: type=gha
                    cache-to: type=gha

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
