name: Publish bot

on:
    push:
        branches:
            - main
    workflow_dispatch: {}

jobs:
    publish:

        runs-on: ubuntu-latest

        concurrency:
            group: ${{ github.ref }}-release
            cancel-in-progress: true

        steps:
        -   uses: actions/checkout@v3

        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v3

        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Login to Github packages
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

        -   name: Build and push
            id: docker_build
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: ghcr.io/dunste123/io:latest
                cache-from: type=gha
                cache-to: type=gha

        -   name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}

        -   name: Trigger dev webhook
            uses: distributhor/workflow-webhook@v3
            env:
                webhook_url: ${{ secrets.WEBHOOK_URL }}
